### ISSUE TITLE
string attribute in <tree>

### ISSUE THREAD

**Issue by celm1990** [mjavint/odoo-shortcuts#1]
Hola, estoy usando la extension junto con herramientas de OCA(pre-commit, flake-odoo, etc) para versiones mas recientes de Odoo(creo desde la 14) no es necesario agregar un string a las vistas tree(igual para la form, search, etc)

Esta extension crea la vista con un string que  luego me toca estar quitandolo manualmente, seria ideal que ya no venga ese string en la definicion de la vista

![image](https://github.com/mjavint/odoo-shortcuts/assets/7775116/9bd84b2b-9a94-4360-9382-81f9c3cf434b)

La vista `search` viene por defecto con esto
```
<search string="Bla bla bla">
                <group expand="1" string="Group By">
                    <filter string="Name" name="name" domain="[]" context="{'group_by':'name'}"/>
                </group>
            </search>
```

Pero es raro que se agrupe por el campo `name`, mi sugerencia es que venga con _filtro de campo name_, no con agrupacion
```
<search string="Bla bla bla">
    <field name="name" />
</search>
```

**Comment by mjavint** [comment]
Gracias por compartir y mejorar nuestro trabajo. La incidencia a sido resuelta en la versión 0.11.1 de Odoo Shortcuts.
