### ISSUE TITLE
[ FEAT ] Creates inherit views. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#2]
Actually, I can create a related xml view, but most of the time I needs to create an inherit view.  Are there a planning to implement this?

**Comment by mjavint** [comment]
Thanks, we are already working on that functionality

**Comment by mjavint** [comment]
Solved the new functionality in version 0.12.0 of Odoo Shortcuts. Thanks for the contribution colleague
