### ISSUE TITLE
[BUG] Una 'server action' sobreescribe el fichero de vistas donde el modelo sea igual que otro existente. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#3]
Cuando hay una vista existente del mismo modelo que la acción de servidor que se está generando, el nuevo código de la acción sobre escribe los datos anteriores ó completamente reemplaza el fichero existente. 

# Pasos para replicar el problema. 

1. Generar una vista heredada desde "Odoo explorer".  
![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/cb5d99a4-4153-48f1-8a83-0b53832baa08)

2. Generar una acción de servidor del mismo modelo que la vista heredada. 
![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/32199876-40a9-4e63-8fd0-4f0227f7a9f1)
![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/b2f45b6a-966e-4401-8024-56d83ab61b98)
![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/05deb114-f195-4142-9a19-9de576e4f155)
![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/0e1a2c2a-29c4-4a39-b91a-a8e662823997)

# Comportamiento esperado.

- Opción 1 : Que se cree un nuevo fichero `action_servers.xml`
- Opción 2 : Que se agregue al final de la vista existente.   

## Notas adicionales. 

El apartado "data" del manifest registra múltiples veces el nuevo fichero xml creado.

**Comment by mjavint** [comment]
Se han corregido los issues descritos en este Post con las dos opciones, ademas del registro multiple en el manifest de los xml. Gracias por tus descripciones fue de gran ayuda
