### ISSUE TITLE
[ BUG ] El `model_id` y `bindig_id` no obtienen el nombre del módulo proporcionado por el usuario. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#4]
# Pasos para replicar el problema. 

- Se genera una acción se servidor desde "Odoo Explorer". 
- Se introduce como modelo `hr.employee`
- Se genera el siguiente código: 
```xml


 <record id="model_hr_employee_action" model="ir.actions.server">
        <field name="name">Generate Uuid</field>
        <field name="model_id" ref="account.model_hr_employee"/>
        <field name="binding_model_id" ref="account.model_hr_employee"/>
        <field name="binding_view_types">form</field>
        <field name="state">code</field>
        <field name="code">action = records.generate_uuid()</field>
    </record>


```

Donde se obtiene `account` como nombre de módulo. 

# Resultado esperado. 

- Se espera que el nombre del módulo se tome desde el campo ingresado cuando se respeta el estandar `nombre_modulo.modelo`.
- Cuando no respete esta estructura se puede dejar opcionalmente la leyenda `module_name_here.model_...`-

**Comment by mjavint** [comment]
Se ha agregado un nuevo stage al quickpick preguntando por el modulo, gracias por detallar bien el issue
