### ISSUE TITLE
Traducciones innecesarias

### ISSUE THREAD

**Issue by celm1990** [mjavint/odoo-shortcuts#6]
Cuando usas el autocompletado de campos, se usa funcion de traduccion, pero Odoo por defecto siempre traduce el string y las opciones de selecction, creo que es innecesario y redundante usar la funcion de traduccion.

Podriamos quitar el `_()` en la definicion de campos?
```
field_name = fields.Many2one(
        string=_('field_name'),
        comodel_name='model.name',
    )
```
Quedaria solo como
```
field_name = fields.Many2one(
        string='field_name',
        comodel_name='model.name',
    )
```

**Comment by RafaelAngelRamirez** [comment]
> Cuando usas el autocompletado de campos, se usa funcion de traduccion, pero Odoo por defecto siempre traduce el string y las opciones de selecction, creo que es innecesario y redundante usar la funcion de traduccion.
> 
> Podriamos quitar el `_()` en la definicion de campos?
> 
> ```
> field_name = fields.Many2one(
>         string=_('field_name'),
>         comodel_name='model.name',
>     )
> ```
> 
> Quedaria solo como
> 
> ```
> field_name = fields.Many2one(
>         string='field_name',
>         comodel_name='model.name',
>     )
> ```

No si lo que buscas es generar archivos de traducción po.

**Comment by celm1990** [comment]
> 
> No si lo que buscas es generar archivos de traducción po.

No me refiero a eso, sino que en el string de cada field le agrega `_()` y eso es innecesario, Odoo se encarga de agregar el `string` y las `opciones de campos selection` sin necesidad de agregar la funcion de traduccion `_()`
Sugiero es quitar esa funcion en los string de los campos
![image](https://github.com/mjavint/odoo-shortcuts/assets/7775116/43b23a8b-f1fb-4068-8857-3393d14ea5ee)

**Comment by mjavint** [comment]
Se corrigió en la versión 0.15.0
