### ISSUE TITLE
[BUG] El id del record en una vista heredada provoca un error de módulo no instalado. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#7]
# Problema

Cuando se crea una vista heredada, el id del record incluye un punto dentro de su definición, lo que provoca que odoo intente buscar un módulo que no existe. 

```xml

<?xml version="1.0" encoding="utf-8"?>
  <odoo>
      
    <!-- View commission.settlement form -->
    <record id="view_commission_settlement_views.xml_form" model="ir.ui.view">
        <field name="name">view.commission.settlement.form</field>
        <field name="model">commission.settlement</field>
        <field name="inherit_id" ref="commission.view_settlement_form"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='line_ids']/tree/field[@name='date']" position="after">
              <field name="margin" /> 
              <field name="quantity" /> 
              <field name="purchase_price" /> 


            </xpath>
        </field>
    </record>

  </odoo>
  
  ```

El problema esta en `id="view_commission_settlement_views.xml_form"`. 

# Replicar el problema: 

1. Desde odoo explorer crear un nuevo xml. 
2. Seleccionar inherit view. 
3. Agregar el nombre del módelo. 
4. Seleccionar vistas para generar (form, list, etc)
5. Se crea una vista con el id dañado. 
6. Al instalar el módulo o actualizarlo se muestra el siguiente error. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 504, in _tag_record
    self._test_xml_id(rec_id)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 250, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
AssertionError: The ID "view_commission_settlement_views.xml_form" refers to an uninstalled module

```

# Solución 

Cambiar el punto por un guión bajo. 

# Versiones afectadas

Actualmente solo probado en v15.

**Comment by mjavint** [comment]
Gracias por tus observaciones, resolveremos lo mas pronto que podamos este error

**Comment by mjavint** [comment]
Ya se solucionó el error en la versión 0.13.1, cuando esté disponible actualice la extensión
