### ISSUE TITLE
[BUG] Al crear un wizard la linea de importación dentro del manifest es diferente del nombre creado. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#8]
# Problema
Al crear un nuevo wizard desde el Odoo Explorer la línea para el registro del archivo xml en la propiedad data difiere del nombre dado al archivo como tal. 

```python
"data": [
       "..."
        "wizard/maintenance_plan_wizard_views.xml"
    ],
```

![image](https://github.com/mjavint/odoo-shortcuts/assets/27775245/40c28c81-fd33-4e6d-a9be-c38c58658f1b)

# Replicar el problema

1. Desde odoo explorer crear un nuevo wizard.  
2. Agregar el nombre del modelo.
3. Seleccionar vistas para generar. 
4. Se crea un wizard con nombre de xml diferente al registrado en la propiedad data del manifest. 

# Solución

Remover `_views` del string para registro en el manifest.

**Comment by mjavint** [comment]
Se corrigió en la versión 0.15.0

**Comment by celm1990** [comment]
Hubiera preferido mantener el sufijo `_views` y mas bien el nombre del archivo agregarle ese sufijo en lugar de quitarlo
```
my_wizard.py
my_wizard_views.xml
```
Esta mucho mas apegado a las guideslines de Odoo
https://www.odoo.com/documentation/17.0/contributing/development/coding_guidelines.html#file-naming

**Comment by RafaelAngelRamirez** [comment]
> Hubiera preferido mantener el sufijo `_views` y mas bien el nombre del archivo agregarle ese sufijo en lugar de quitarlo
> 
> ```
> my_wizard.py
> my_wizard_views.xml
> ```
> 
> Esta mucho mas apegado a las guideslines de Odoo https://www.odoo.com/documentation/17.0/contributing/development/coding_guidelines.html#file-naming

Estoy en contra de las guidelines con respecto a los wizard por que tienes un "view" fuera de la carpeta "view", que lo convierte en algo cercano a un anti-paterrn. En mi opinión un wizard siempre va casado a un xml que debe contener todo lo relacionado al modelo, no únicamente un view.

**Comment by celm1990** [comment]
bueno entre las guideslines de Odoo y OCA, prefiero las de OCA y respecto a wizard lo hacen sin el sufijo views, gracias x los comentarios y cambios en la extension
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#17complete-structure
