### ISSUE TITLE
[BUG] Al importar permiso de nuevo model a ir.model.access.csv no se agrega una nueva linea si no existe. 

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [mjavint/odoo-shortcuts#9]
# Problema
Después de crear un wizard (ó algun modelo) es necesario añadir sus permisos de accesos al fichero `ir.model.access.csv`. Cuando existe el fichero, pero no tiene una línea nueva, se agrega al final de la línea, lo que provoca que no sea tomado en cuenta. 

```csv
id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_maintenance_tipo_personalizado,Mantenimiento - Lista materiales,maintenance_plan_extended.model_maintenance_material_list,base.group_user,1,1,1,1access_maintenance_plan_wizard_manager,maintenance_plan_wizard_manager,model_maintenance_plan_wizard,,1,1,1,1

``` 

> No se crea una nueva línea. 

# Replicar

1. Desde odoo explorer crear un nuevo modelo (wizard)
2. Seleccionar las vistas. 
3. Abrir el nuevo modelo creado. 
4. Generar los permisos desde los accesos directos. 
5. Se crea un permiso en la misma línea cuando el fichero no tiene una nueva línea en blanco. 

# Solución

Verificar si hay una nueva línea en el fichero de permisos, de lo contrario agregar junto con la nueva línea.

**Comment by mjavint** [comment]
Se corrigió en la versión 0.15.0

**Comment by mjavint** [comment]
Se corrigió en la versión 0.15.0
